global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx , http_2xx_with_latency, http_response_time, ssl_expiry]
    static_configs:
      - targets: 
        - https://genz.ad
        - https://api.genz.ad
        - https://staging.genz.ad
        - https://staging.api.genz.ad
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: 'github-actions'
    static_configs:
      - targets: ['localhost:9091'] 

  - job_name: 'dora_metrics'
    static_configs:
      - targets: ['localhost:9231']
